import time

Name = input('Please Give Name: ')
msg = "Hi, " + Name
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(1)
print(msg)
time.sleep(2)
Hi = input('Say hi back: ')
time.sleep(5)
print('Wow you wasted time in your life')